version: "3.9"
services:
  ui:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      VITE_APP_API_ENDPOINT: http://localhost:8000
      VITE_APP_USER_POOL_ID: us-east-1_se088spsj
      VITE_APP_USER_POOL_CLIENT_ID: 4lh281rsu04aghtmt88vkuh8fd
      VITE_APP_REGION: us-east-1
      VITE_APP_USE_STREAMING: false # ローカル開発時は websocket を利用しない
      VITE_APP_WS_ENDPOINT: ws://localhost:8080
    volumes:
      - "./frontend/src:/app/src"

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000
    environment:
      DDB_ENDPOINT_URL: http://dynamodb-local:8080
      TABLE_NAME: ConversationTable
      # DDB_ENDPOINT_URL: https://dynamodb.us-east-1.amazonaws.com
      # TABLE_NAME: BedrockChatStack-DatabaseConversationTable03F3FD7A-RMCEHJG7OV56
      # Bedrock 向けの設定
      BEDROCK_REGION: us-east-1
      # AWS_ACCESS_KEY_ID: 
      # AWS_SECRET_ACCESS_KEY: 
      REGION: us-east-1
      ACCOUNT: 916537346432
      # TABLE_ACCESS_ROLE_ARN: 'arn:aws:iam::916537346432:role/BedrockChatStack-DatabaseTableAccessRole59AAC05E-6GgnGxFGAur5'
    volumes:
      - "~/.aws:/root/.aws" # ローカルのクレデンシャルの利用に必要
      - "./backend/app:/backend/app"
  #  depends_on:
  #    - dynamodb-local
 

  dynamodb-local:
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:1.22.0
    command: "-jar DynamoDBLocal.jar -port 8080"
    ports:
      - 8080:8080

  # # 初期テーブル作成用のコンテナ
  # init-dynamodb:
  #   image: public.ecr.aws/aws-cli/aws-cli:latest
  #   environment:
  #     AWS_REGION: us-east-1
  #     AWS_ACCESS_KEY_ID: key
  #     AWS_SECRET_ACCESS_KEY: key
  #   depends_on:
  #     - dynamodb-local
  #   command: >
  #     dynamodb create-table --table-name ConversationTable
  #     --attribute-definitions
  #       AttributeName=UserId,AttributeType=S
  #       AttributeName=ConversationId,AttributeType=S
  #     --key-schema
  #       AttributeName=UserId,KeyType=HASH
  #       AttributeName=ConversationId,KeyType=RANGE
  #     --global-secondary-indexes
  #       IndexName=ConversationIdIndex,KeySchema=[{'AttributeName=ConversationId,KeyType=HASH'}],Projection={ProjectionType=ALL}
  #     --billing-mode PAY_PER_REQUEST
  #     --endpoint-url http://dynamodb-local:8080

  # DynamoDB Local 向けの GUI
  #dynamodb-admin:
  #  image: aaronshaf/dynamodb-admin
  #  ports:
  #    - 8001:8001
  #  depends_on:
  #    - dynamodb-local
  #  environment:
  #    AWS_REGION: us-east-1
  #    AWS_ACCESS_KEY_ID: key
  #    AWS_SECRET_ACCESS_KEY: key
  #    DYNAMO_ENDPOINT: http://dynamodb-local:8080
